baseURL = 'https://andyy171.github.io/knowledge-hub'
languageCode = 'vi-VN'
title = 'Personal Knowledge Hub'
relativeURLs = true
canonifyURLs = true

# Build performance
timeout = '30s'
enableGitInfo = true
enableEmoji = true

# Content management (Hugo >= v0.128)
[pagination]
  pagerSize = 50
  path = 'page'

# Markdown processing
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'github'
    lineNos = true
    tabWidth = 2

# Taxonomy
[taxonomies]
  category = 'categories'
  tag = 'tags'
  author = 'authors'

# Site parameters
[params]
  description = 'Personal Knowledge Repository'
  author = 'Duy Anh'
  dateFormat = '02/01/2006'
  search = true
  rating = true
  
# Menu structure
[[menu.main]]
  name = 'Linux'
  url = '/linux/'
  weight = 10

[[menu.main]]
  name = 'Kubernetes'
  url = '/kubernetes/'
  weight = 20

[[menu.main]]
  name = 'Backend'
  url = '/backend/'
  weight = 30

[[menu.main]]
  name = 'Networking'
  url = '/networking/'
  weight = 40

# Output formats
[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]
